### ISSUE TITLE
Implement Knapsack selction

### ISSUE THREAD

**Issue by rajarshimaitra** [Bitshala-Incubator/rust-coinselect#2]
Implement knapsack selection algorithm and add tests via suitable test vectors.

**Comment by delcin-raj** [comment]
The implementation should closely follow the [thesis](https://murch.one/erhardt2016coinselection.pdf) of Mark Erhard.
The top level function `select_coin_knapsack` should follow line 7-9 of Algorithm.
The following should be computed in the `select_coin_knapsack` function
  1. adjusted_target which is  [necessary_target](https://github.com/Bitshala-Incubator/rust-coinselect/blob/main/src/lib.rs#L163) plus the min_absolute_fee.
  1. smaller_coins  by sorting the inputs in descending order of value and finding the first index whose value is smaller than the adjusted_target.
 
function `knapsack` should follow Algorithm 3.
Use HashSet<usize> for storing the selections.
* There are total of 1000 tries, for each of them start with a fresh empty set of `selectedUTXOs`.
* Line 17 requires to clone the `selectedUTXOs` HashSet.
* /\ refers to logical AND, \/ refers to logical OR.

Any questions you have comment below.
