### ISSUE TITLE
Implement Lowest Larger Selection

### ISSUE THREAD

**Issue by delcin-raj** [Bitshala-Incubator/rust-coinselect#21]
This algorithm should work in the following way.

* transform the inputs into [(index, input)] form to preserve the original index
* sort the above in ascending order based on the `value` of the input
* Do binary search to find the index of the sorted array which has value less than the target
* Follow simple_random_draw and fifo to learn about how to use effective value, calculate waste etc.,
* Write some tests to make sure that you are getting the expected answer.

Reference implementation in javascript can be found [here](https://github.com/bcoin-org/bcoin/blob/0c18028cd333bef8b0939ada8b56ae3911fd0c26/lib/wallet/coinselector.js#L667)

**Comment by AguirreIF** [comment]
Code added in #22.
