### ISSUE TITLE
[test] `select_coin` function should return the algorithm used

### ISSUE THREAD

**Issue by rishkwal** [Bitshala-Incubator/rust-coinselect#39]
Currently there is no way of knowing which coin selection algorithm was used by the `select_coin` function without comparing the outputs individually. It might be useful to know which algorithm was used to get the output by returning the algorithm used.

**Comment by delcin-raj** [comment]
This might be added complexity for users, who don't care about from which algorithm the result comes.
Basically we are choosing the result with lowest waste metric.

**Comment by rishkwal** [comment]
I understand we are choosing the result with the lowest waste metric but this gives no information about the algorithm used that might be useful for additional analysis. Maybe we can keep the functionality same and let users who want more information add an optional flag to the function call?

**Comment by delcin-raj** [comment]
Can’t the data analyst do that themselves with their data and calling the
individual functions separately?
To me the user shouldn’t be thinking or asking these questions in the first
place.
Our crate should not add complexity for the sake of it.
The documentation should clearly explain how each individual algorithm
behaves.

Maybe you can do such experimentation and help with the documentation.
Will greatly appreciate it.
