### ISSUE TITLE
Publishing to crates.io

### ISSUE THREAD

**Issue by delcin-raj** [Bitshala-Incubator/rust-coinselect#63]
Check whether the project is ready to be published based on https://doc.rust-lang.org/cargo/reference/publishing.html.

Create issues if needed as paste them as comment in this issue below, we will merge once every concern is addressed.

Make sure that it adheres to the guidelines https://rust-lang.github.io/api-guidelines/

**Comment by Musab1258** [comment]
@delcin-raj, can I work on this?

**Comment by delcin-raj** [comment]
Yes, multiple people can work on this.
If you find any discrepancies raise a separate issue and a corresponding PR
and link them in this issue.

**Comment by Musab1258** [comment]
Ok.
