### ISSUE TITLE
Modify the bitcoin example with sensible values

### ISSUE THREAD

**Issue by delcin-raj** [Bitshala-Incubator/rust-coinselect#76]
In the example of bitcoin crate, specifically the `CoinselectOpt` was generated randomly.
But those should  be crafted according to the bitcoin transaction fields and are to be determined deterministically.

**Comment by delcin-raj** [comment]
@NeoZ666 please fix this issue.

**Comment by NeoZ666** [comment]
#84 here

**Comment by NeoZ666** [comment]
We can close this now
